apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alert-rules.yml: |
    groups:
    - name: argocd-alerts
      rules:
      # Alert if application health is not "Healthy"
      - alert: ArgoCDAppUnhealthy
        expr: argocd_app_info{health_status!="Healthy"} == 1
        for: 30s
        labels:
          severity: warning
          component: argocd
        annotations:
          summary: "Argo CD Application {{ $labels.name }} is unhealthy"
          description: "Application {{ $labels.name }} in namespace {{ $labels.namespace }} has health status {{ $labels.health_status }} for more than 30 seconds."
          
      # Alert if sync status is not "Synced"  
      - alert: ArgoCDAppOutOfSync
        expr: argocd_app_info{sync_status!="Synced"} == 1
        for: 30s
        labels:
          severity: warning
          component: argocd
        annotations:
          summary: "Argo CD Application {{ $labels.name }} is out of sync"
          description: "Application {{ $labels.name }} in namespace {{ $labels.namespace }} has sync status {{ $labels.sync_status }} for more than 30 seconds."
          
      # Alert if no sync operations have occurred recently
      - alert: ArgoCDAppNoRecentSync
        expr: increase(argocd_app_sync_total[24h]) == 0
        for: 24h
        labels:
          severity: info
          component: argocd
        annotations:
          summary: "Argo CD Application {{ $labels.name }} has not synced in 24 hours"
          description: "Application {{ $labels.name }} has not performed any sync operations in the last 24 hours."
